modLoader="javafml"
loaderVersion="[33,)"
license="All rights reserved"
[[mods]]
modId="hooty"
version="1.16.2-0.0.1"
displayName="Hooty Mod"
authors="Jagm"
description='''
Adds Hooty from the Disney cartoon The Owl House. He will follow you at an uncomfortable distance, and cannot be killed.
'''
[[dependencies.hooty]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.hooty]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
